version: "3.7"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      
  database_msclient:
    image: postgres
    container_name: database_msclient       
    ports:
      - 5431:5432
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin 
      - POSTGRES_DB=db_msclient
    volumes: 
      - pgdata:/data/postgres    
  app:
    build: .
    container_name: ms_client
    ports: 
      - 3000:3000
    volumes: 
      - .:/usr/app    
    links:
      - database_msclient
    depends_on:
      - database_msclient

volumes:
  pgdata:
    driver: local